from __future__ import annotations

import json
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any

from .adapters import collect_source
from .health import build_source_health
from .http_client import AcquisitionClient, utc_now
from .normalizer import (
    build_canonical_fixtures,
    build_canonical_players,
    build_canonical_teams,
    build_evidence_index,
    build_lineage_catalog,
)
from .polling import attach_poll_result, carry_forward_skipped, deadline_window_active, poll_decision
from .registry import dependency_layers, load_registry, resolved_registry_snapshot, source_map
from .store import (
    EVIDENCE,
    HEALTH,
    MANIFEST,
    NORMALIZED,
    load_previous_sources,
    prune_inactive_sources,
    write_json,
    write_source,
)


def _isolated_failure(source: dict[str, Any], exc: Exception) -> dict[str, Any]:
    return {
        "schema_version": 3,
        "source_id": source["id"],
        "source_name": source["name"],
        "category": source["category"],
        "adapter": source["adapter"],
        "critical": bool(source.get("critical")),
        "independence_group": source.get("independence_group"),
        "checked_at": utc_now(),
        "health": "RED" if source.get("critical") else "AMBER",
        "availability": "UNAVAILABLE",
        "effective_state": "MISSING",
        "changed": None,
        "error": type(exc).__name__,
        "governance": {
            "data_only": True,
            "decision_authority": "NONE",
            "prediction_authority": "NONE",
            "optimizer_authority": "NONE",
            "isolated_failure": True,
            "values_not_invented": True,
        },
    }


def _dependency_payloads(source: dict[str, Any], results: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {
        str(dependency): results[str(dependency)]
        for dependency in source.get("depends_on") or []
        if str(dependency) in results
    }


def run() -> dict[str, Any]:
    config = load_registry()
    sources = list(config["sources"])
    source_ids = [str(source["id"]) for source in sources]
    by_id = source_map(config)
    layers = dependency_layers(config)
    previous = load_previous_sources()
    pruned_runtime_source_files = prune_inactive_sources(source_ids)
    client = AcquisitionClient(config["policy"])
    results: dict[str, dict[str, Any]] = {}
    started = time.perf_counter()

    scheduler_interval_minutes = max(
        1,
        int((config.get("cadence") or {}).get("scheduler_interval_minutes") or 60),
    )
    deadline_window = deadline_window_active(
        previous,
        hours=int(config["policy"].get("deadline_window_hours") or 48),
    )

    decisions = {
        source["id"]: poll_decision(
            source,
            previous.get(source["id"]),
            deadline_window=deadline_window,
            max_attempts_per_request=client.retry_attempts,
            scheduler_interval_minutes=scheduler_interval_minutes,
        )
        for source in sources
    }

    for source in sources:
        decision = decisions[source["id"]]
        if not decision["due"]:
            results[source["id"]] = carry_forward_skipped(
                source,
                previous.get(source["id"]),
                decision,
            )

    configured_source_workers = max(
        1,
        int(config["policy"].get("source_workers") or config["policy"].get("max_workers") or 12),
    )
    peak_source_workers = 1

    # Dependency layers are generated by the validated registry DAG. Independent
    # sources in a layer run concurrently; only declared dependencies serialize.
    for layer in layers:
        due_sources = [
            by_id[source_id]
            for source_id in layer
            if decisions[source_id]["due"]
        ]
        if not due_sources:
            continue
        layer_workers = max(1, min(len(due_sources), configured_source_workers))
        peak_source_workers = max(peak_source_workers, layer_workers)
        with ThreadPoolExecutor(max_workers=layer_workers) as pool:
            futures = {
                pool.submit(
                    collect_source,
                    source,
                    client,
                    previous=previous.get(source["id"]),
                    dependency_payloads=_dependency_payloads(source, results),
                ): source
                for source in due_sources
            }
            for future in as_completed(futures):
                source = futures[future]
                decision = decisions[source["id"]]
                try:
                    payload = future.result()
                except Exception as exc:
                    payload = _isolated_failure(source, exc)
                results[source["id"]] = attach_poll_result(
                    source,
                    payload,
                    previous.get(source["id"]),
                    decision,
                )

    for source in sources:
        if source["id"] not in results:
            results[source["id"]] = _isolated_failure(
                source,
                RuntimeError("source_missing_after_dependency_execution"),
            )
        write_source(source["id"], results[source["id"]])

    official = results.get("official_fpl") or _isolated_failure(
        by_id["official_fpl"],
        RuntimeError("official_fpl_missing_from_results"),
    )

    write_json(NORMALIZED / "canonical_players.json", build_canonical_players(official, source_ids))
    write_json(NORMALIZED / "canonical_teams.json", build_canonical_teams(official))
    write_json(NORMALIZED / "canonical_fixtures.json", build_canonical_fixtures(official))
    write_json(EVIDENCE / "lineage.json", build_lineage_catalog(config))
    write_json(EVIDENCE / "latest_index.json", build_evidence_index(results))
    write_json(EVIDENCE / "resolved_registry.json", resolved_registry_snapshot(config))

    health = build_source_health(config, results)
    write_json(HEALTH / "source_health.json", health)

    elapsed = round((time.perf_counter() - started) * 1000.0, 3)
    critical_failures = [
        source["id"]
        for source in sources
        if source.get("critical") and results[source["id"]].get("health") == "RED"
    ]
    durations = {
        source_id: payload.get("duration_ms")
        for source_id, payload in results.items()
        if payload.get("duration_ms") is not None
    }
    skipped = {
        source_id: (payload.get("polling") or {}).get("reason")
        for source_id, payload in results.items()
        if (payload.get("polling") or {}).get("skipped") is True
    }
    activation = dict(config.get("activation") or {})
    activation["pruned_runtime_source_files"] = pruned_runtime_source_files
    policy = dict(config.get("policy") or {})
    due_source_count = sum(bool(decision["due"]) for decision in decisions.values())

    manifest = {
        "schema_version": 3,
        "engine": config["engine"],
        "season": config["season"],
        "generated_at": utc_now(),
        "elapsed_ms": elapsed,
        "source_count": len(sources),
        "source_ids": source_ids,
        "activation": activation,
        "overall": "RED" if critical_failures else health["overall"],
        "health_counts": health["counts"],
        "critical_failures": critical_failures,
        "performance": {
            "source_workers": peak_source_workers,
            "configured_source_workers": configured_source_workers,
            "request_workers_per_source": client.request_workers,
            "source_duration_ms": durations,
            "slowest_source_ms": max(durations.values()) if durations else None,
            "dependency_layers": layers,
            "unrelated_sources_are_not_dependency_blocked": True,
        },
        "polling": {
            "adaptive": True,
            "scheduler_interval_minutes": scheduler_interval_minutes,
            "deadline_window_active": deadline_window,
            "deadline_window_hours": int(policy.get("deadline_window_hours") or 48),
            "due_source_count": due_source_count,
            "skipped_source_count": len(skipped),
            "skipped_sources": skipped,
        },
        "paths": {
            "current_sources": "data/v6/current/",
            "health": "data/v6/health/source_health.json",
            "canonical_players": "data/v6/normalized/canonical_players.json",
            "canonical_teams": "data/v6/normalized/canonical_teams.json",
            "canonical_fixtures": "data/v6/normalized/canonical_fixtures.json",
            "lineage": "data/v6/evidence/lineage.json",
            "evidence_index": "data/v6/evidence/latest_index.json",
            "resolved_registry": "data/v6/evidence/resolved_registry.json",
        },
        "governance": {
            "decision_authority": policy["decision_authority"],
            "prediction_authority": policy["prediction_authority"],
            "optimizer_authority": policy["optimizer_authority"],
            "data_only": bool(policy["data_only"]),
            "no_cross_source_averaging": bool(policy.get("no_cross_source_averaging")),
            "no_fabrication": bool(policy["no_fabrication"]),
            "source_failures_are_isolated": bool(policy.get("source_failures_are_isolated")),
            "request_failures_are_isolated": bool(policy.get("request_failures_are_isolated")),
            "unchanged_upstream_is_not_degraded": True,
            "last_good_cache_hydrated_by_workflow": True,
            "adaptive_polling_is_registry_driven": True,
            "active_source_pruning_is_registry_driven": True,
            "dependency_order_is_registry_driven": True,
            "resolved_registry_is_published": True,
            "daily_budget_timezone": "Asia/Jakarta",
            "weather_is_context_only": True,
            "weather_direct_xpts_multiplier": False,
            "weather_alone_can_trigger_transfer": False,
        },
    }
    write_json(MANIFEST, manifest)
    return manifest


def main() -> int:
    print(json.dumps(run(), ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
